<?php

namespace AppBundle\Repository;

/**
 * CeresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CeresRepository extends \Doctrine\ORM\EntityRepository
{
}
