AppBundle\Entity\Dates:
    type: entity
    table: Dates
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dates:
            type: string
            nullable: false
            length: 11
            options:
                fixed: false
    lifecycleCallbacks: {  }
